Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8090, host: 8090

  config.vm.synced_folder "../", "/apache_skeleton"

  config.vm.provision "shell", path: "install_Apache.sh"
end
