Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8090, host: 8090

  config.vm.provider :virtualbox do |vb|
    # suggested fix for slow network performance
    # see https://github.com/mitchellh/vagrant/issues/1807
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end


  config.vm.synced_folder "../", "/apache_skeleton"

  config.vm.provision "shell", path: "install_Apache.sh"
end
